 Project Objectives

- Understand the patient-flow and satisfaction data
- Assess data quality
- Perform statistical analysis
- Identify important patterns and relationships
- Generate meaningful business insights
- Build a machine learning model to predict patient satisfaction
- Evaluate and explain the model
- Develop a Power BI dashboard

2. Business Problem

Hospitals collect large amounts of patient-flow and patient-experience
data. However, raw data alone does not clearly explain what factors are
associated with patient satisfaction.

This project aims to analyze patient experience and operational data
to identify important patterns, understand potential factors associated
with satisfaction, and develop a predictive analytics solution that can
support hospital management.
Then add one more Markdown cell: Business

3. Business Questions

The analysis will answer the following questions:

1. What is the overall distribution of patient satisfaction?

2. Which departments or patient-flow categories show differences
   in satisfaction?

3. Is waiting time associated with patient satisfaction?

4. Which operational or service-related variables are associated
   with satisfaction?

5. Are there significant differences in satisfaction between
   different patient groups?

6. Are there outliers or unusual patterns in patient-flow data?

7. Which factors are most useful for predicting patient satisfaction?

8. Can a machine learning model identify patients who may have
   lower satisfaction?

9. What actionable insights can hospital management obtain from
   the analysis?

In [59]:
import pandas as pd

In [60]:
df=pd.read_csv("/content/drive/MyDrive/datasets2026/healthcare_analytics_patient_flow_data.csv")

In [61]:
df.head(30)

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36
5,736-98-3342,9/9/2024,12:05:00 PM,B. Glasman,Male,27,Asian,NaN,Not Admission,NaN,52
6,634-04-5264,9/9/2024,5:25:00 PM,R. Possek,Female,70,White,General Practice,Not Admission,NaN,57
7,237-07-3349,9/9/2024,7:46:00 PM,H. Cloake,Female,64,Two or More Races,General Practice,Not Admission,NaN,13
8,695-54-0916,9/9/2024,12:34:00 PM,G. Tregonna,Female,69,Two or More Races,General Practice,Not Admission,NaN,48
9,536-68-0475,9/9/2024,1:14:00 PM,T. Shillaker,Female,25,African American,General Practice,Admission,6.0,14
10,166-50-3397,9/9/2024,9:47:00 AM,S. Hebblewaite,Male,43,White,NaN,Admission,NaN,15
11,800-71-0609,9/9/2024,12:57:00 AM,X. McCart,Female,1,Declined to Identify,NaN,Not Admission,NaN,17
12,223-54-0736,9/9/2024,12:34:00 PM,B. Carman,Female,51,Two or More Races,NaN,Admission,7.0,35
13,792-04-6423,9/9/2024,2:00:00 PM,K. Brittan,Female,59,White,General Practice,Admission,NaN,56
14,898-30-3232,9/9/2024,10:47:00 AM,L. Week,Female,33,Native American/Alaska Native,NaN,Not Admission,2.0,42
15,255-19-2946,9/9/2024,11:18:00 AM,Q. Dalglish,Female,59,White,NaN,Not Admission,NaN,45
16,193-27-1560,9/9/2024,2:19:00 AM,E. Norcliff,Female,12,White,NaN,Admission,NaN,17
17,684-59-6729,9/9/2023,6:44:00 AM,M. Harsent,Female,31,African American,NaN,Not Admission,NaN,43
18,419-20-6236,9/9/2023,9:54:00 PM,L. Scargle,Male,46,Declined to Identify,NaN,Not Admission,NaN,26
19,867-15-2683,9/9/2023,7:15:00 PM,G. Edington,Male,14,Declined to Identify,Orthopedics,Not Admission,NaN,36
20,308-46-0712,9/9/2023,3:09:00 PM,X. Seabrocke,Female,8,Asian,NaN,Not Admission,NaN,60
21,215-29-2936,9/9/2023,1:19:00 PM,B. Emberson,Female,44,African American,NaN,Admission,NaN,53
22,693-70-1074,9/9/2023,3:28:00 PM,P. McCloud,Male,49,Asian,NaN,Not Admission,NaN,55
23,824-34-1887,9/9/2023,11:21:00 PM,A. Coushe,Male,42,African American,NaN,Admission,NaN,54
24,649-56-1131,9/9/2023,6:46:00 PM,H. Northeast,Male,7,African American,NaN,Admission,NaN,29
25,552-80-5445,9/9/2023,12:28:00 PM,U. Bento,Female,17,African American,NaN,Not Admission,3.0,37
26,168-40-7318,9/9/2023,9:24:00 PM,X. Wiseman,Male,69,Asian,NaN,Not Admission,NaN,40
27,338-56-5549,9/9/2023,7:25:00 PM,F. Cod,Male,56,African American,Orthopedics,Admission,NaN,59
28,288-66-5811,9/9/2023,12:20:00 AM,K. Beseke,Male,63,Declined to Identify,General Practice,Not Admission,0.0,50
29,495-29-7252,9/9/2023,10:31:00 PM,A. Belt,Female,21,African American,NaN,Not Admission,NaN,23

In [62]:
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)

(9216, 11)
['Patient Id', 'Patient Admission Date', 'Patient Admission Time', 'Merged', 'Patient Gender', 'Patient Age', 'Patient Race', 'Department Referral', 'Patient Admission Flag', 'Patient Satisfaction Score', 'Patient Waittime']
Patient Id                     object
Patient Admission Date         object
Patient Admission Time         object
Merged                         object
Patient Gender                 object
Patient Age                     int64
Patient Race                   object
Department Referral            object
Patient Admission Flag         object
Patient Satisfaction Score    float64
Patient Waittime                int64
dtype: object

4. Data Dictionary

| Column | Data Type | Description | Role |
|---|---|---|---|
| Patient Id | Object | Unique identifier for each patient record | Identifier |
| Patient Admission Date | Object | Date on which the patient was admitted | Date |
| Patient Admission Time | Object | Time of patient admission | Time |
| Merged | Object | Combined admission date/time field | Date-Time |
| Patient Gender | Object | Gender of the patient | Categorical |
| Patient Age | Integer | Age of the patient | Numerical |
| Patient Race | Object | Race/ethnicity category recorded in the dataset | Categorical |
| Department Referral | Object | Department associated with the patient encounter | Categorical |
| Patient Admission Flag | Object | Indicates the admission/visit status recorded in the dataset | Categorical |
| Patient Satisfaction Score | Float | Patient satisfaction score recorded after the encounter | Target / Numerical |
| Patient Waittime | Integer | Patient waiting time | Numerical |

### Initial Analytical Roles

- **Target variable:** Patient Satisfaction Score
- **Numerical variables:** Patient Age, Patient Satisfaction Score, Patient Waittime
- **Categorical variables:** Patient Gender, Patient Race, Department Referral, Patient Admission Flag
- **Date/Time variables:** Patient Admission Date, Patient Admission Time, Merged
- **Identifier:** Patient Id

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  9216 non-null   object
 1   Patient Admission Date      9216 non-null   object
 2   Patient Admission Time      9216 non-null   object
 3   Merged                      9216 non-null   object
 4   Patient Gender              9216 non-null   object
 5   Patient Age                 9216 non-null   int64
 6   Patient Race                9216 non-null   object
 7   Department Referral         3816 non-null   object
 8   Patient Admission Flag      9216 non-null   object
 9   Patient Satisfaction Score  2517 non-null   float64
 10  Patient Waittime            9216 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 792.1+ KB

In [64]:
df.describe()

       Patient Age  Patient Satisfaction Score  Patient Waittime
count  9216.000000                 2517.000000       9216.000000
mean     39.855143                    4.992054         35.259874
std      22.755125                    3.138043         14.735323
min       1.000000                    0.000000         10.000000
25%      20.000000                    2.000000         23.000000
50%      39.000000                    5.000000         35.000000
75%      60.000000                    8.000000         48.000000
max      79.000000                   10.000000         60.000000

In [65]:
#to check whether any missing values in the datasets and to count it
df.isnull().sum()

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
Merged                           0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
dtype: int64

In [66]:
#ok now we want to check the duplicated rows inside the datasets
df.duplicated().sum()

np.int64(0)

In [67]:
#ok now we want to check the unique values
print(df["Patient Id"].nunique())
print("gender")
print(df["Patient Gender"].value_counts())
print("department referral")
print(df["Department Referral"].value_counts())
print("patient admission flag")
print(df["Patient Admission Flag"].value_counts)

9216
gender
Patient Gender
Male           4729
Female         4470
Femaleemale      17
Name: count, dtype: int64
department referral
Department Referral
General Practice    1840
Orthopedics          995
Physiotherapy        276
Cardiology           248
Neurology            193
Gastroenterology     178
Renal                 86
Name: count, dtype: int64
patient admission flag
<bound method IndexOpsMixin.value_counts of 0       Not Admission
1       Not Admission
2       Not Admission
3           Admission
4           Admission
            ...
9211    Not Admission
9212        Admission
9213        Admission
9214    Not Admission
9215    Not Admission
Name: Patient Admission Flag, Length: 9216, dtype: object>

In [68]:
# to check which range to which range
print(df["Patient Age"].min(), "to" ,df["Patient Age"].max())
print(df["Patient Satisfaction Score"].min(), "to" ,df["Patient Satisfaction Score"].max())
print(df["Patient Waittime"].min(), "to" ,df["Patient Waittime"].max())

1 to 79
0.0 to 10.0
10 to 60

In [69]:
#ok now we wanted to create a variable and add all the missing_values
missing_values=df.isnull().sum()
print(missing_values)

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
Merged                           0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
dtype: int64

In [70]:
missing_percentage=(df.isnull().sum() /len(df))*100
print(missing_percentage)

Patient Id                     0.000000
Patient Admission Date         0.000000
Patient Admission Time         0.000000
Merged                         0.000000
Patient Gender                 0.000000
Patient Age                    0.000000
Patient Race                   0.000000
Department Referral           58.593750
Patient Admission Flag         0.000000
Patient Satisfaction Score    72.688802
Patient Waittime               0.000000
dtype: float64

In [71]:
duplicate_count=df.duplicated().sum()
print(duplicate_count)

0

In [72]:
duplicated_patients_id=df["Patient Id"].duplicated().sum()
print(duplicated_patients_id)

0

In [73]:
#ok now we are doing how frequently the satisfaction Score
print(df["Patient Satisfaction Score"].value_counts().sort_index())

Patient Satisfaction Score
0.0     222
1.0     246
2.0     204
3.0     228
4.0     248
5.0     221
6.0     231
7.0     256
8.0     218
9.0     222
10.0    221
Name: count, dtype: int64

In [74]:
print(df["Patient Waittime"].value_counts().sort_index())

Patient Waittime
10    167
11    189
12    170
13    161
14    200
15    195
16    176
17    170
18    159
19    184
20    176
21    168
22    180
23    181
24    162
25    187
26    163
27    201
28    157
29    186
30    217
31    154
32    182
33    193
34    196
35    159
36    203
37    164
38    166
39    183
40    184
41    179
42    184
43    185
44    188
45    197
46    135
47    201
48    190
49    188
50    181
51    185
52    182
53    183
54    170
55    200
56    186
57    181
58    196
59    189
60    183
Name: count, dtype: int64

In [77]:
print(df["Patient Age"].value_counts().sort_index())

Patient Age
1     101
2     125
3     117
4     121
5     110
     ...
75    100
76    113
77    104
78    127
79    120
Name: count, Length: 79, dtype: int64

In [80]:
print(df["Patient Id"].value_counts().sort_index())

Patient Id
100-04-3993    1
100-17-5081    1
100-21-9648    1
100-34-6753    1
100-34-9587    1
              ..
899-73-5432    1
899-89-5599    1
899-89-7946    1
899-92-7948    1
899-98-2466    1
Name: count, Length: 9216, dtype: int64

In [81]:
#now we want to look at the time related columns
print(df["Patient Admission Date"].head())
print(df["Patient Admission Time"].head())
print(df["Merged"].head())

0    9/9/2024
1    9/9/2024
2    9/9/2024
3    9/9/2024
4    9/9/2024
Name: Patient Admission Date, dtype: object
0     9:25:00 AM
1     4:42:00 PM
2    12:14:00 AM
3     8:33:00 PM
4     7:25:00 PM
Name: Patient Admission Time, dtype: object
0       W. Breede
1     Y. Baldetti
2      M. Semerad
3      K. Blaydes
4    F. Dickerson
Name: Merged, dtype: object

In [82]:
print(df[["Patient Admission Date","Patient Admission Time","Merged"]].dtypes)

Patient Admission Date    object
Patient Admission Time    object
Merged                    object
dtype: object

In [84]:
# ok now in the analysis process,we found that the merged coumn is not number ,so we want to
#convert it into the date datetime
df["Merged"].head(10).tolist()

['W. Breede',
 'Y. Baldetti',
 'M. Semerad',
 'K. Blaydes',
 'F. Dickerson',
 'B. Glasman',
 'R. Possek',
 'H. Cloake',
 'G. Tregonna',
 'T. Shillaker']

In [83]:
print(df["Patient Admission Date"].head())
print(df["Patient Admission Time"].head())

0    9/9/2024
1    9/9/2024
2    9/9/2024
3    9/9/2024
4    9/9/2024
Name: Patient Admission Date, dtype: object
0     9:25:00 AM
1     4:42:00 PM
2    12:14:00 AM
3     8:33:00 PM
4     7:25:00 PM
Name: Patient Admission Time, dtype: object

In [85]:
df["Patient Admission Time"]=pd.to_datetime(df["Patient Admission Time"],
                                            format="%I:%M%S %p",
                                            errors="coerce")
print(df["Patient Admission Time"].head())
print(df["Patient Admission Time"].dtype)

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: Patient Admission Time, dtype: datetime64[ns]
datetime64[ns]

In [86]:
df = pd.read_csv("/content/drive/MyDrive/datasets2026/healthcare_analytics_patient_flow_data.csv")

print(df["Patient Admission Time"].head())
print(df["Patient Admission Time"].dtype)

0     9:25:00 AM
1     4:42:00 PM
2    12:14:00 AM
3     8:33:00 PM
4     7:25:00 PM
Name: Patient Admission Time, dtype: object
object

In [87]:
print(df["Patient Admission Time"].head(10).tolist())

['9:25:00 AM', '4:42:00 PM', '12:14:00 AM', '8:33:00 PM', '7:25:00 PM', '12:05:00 PM', '5:25:00 PM', '7:46:00 PM', '12:34:00 PM', '1:14:00 PM']

In [88]:
df["Patient Admission Time"] = pd.to_datetime(
    df["Patient Admission Time"],
    errors="coerce"
)

/tmp/ipykernel_3793/2915993006.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Patient Admission Time"] = pd.to_datetime(

In [89]:
#justt converting it explicitly
df["Patient Admission Time"] = pd.to_datetime(
    df["Patient Admission Time"],
    format="%I:%M:%S %p",
    errors="coerce"
)

In [90]:
print(df["Patient Admission Time"].isnull().sum())

0

In [91]:
df["Patient Admission Date"]=pd.to_datetime(
    df["Patient Admission Date"],
    errors="coerce"
)

In [92]:
print(df["Patient Admission Time"].head())
print("Missing time values:", df["Patient Admission Time"].isna().sum())
print("Data type:", df["Patient Admission Time"].dtype)

0   2026-09-23 09:25:00
1   2026-09-23 16:42:00
2   2026-09-23 00:14:00
3   2026-09-23 20:33:00
4   2026-09-23 19:25:00
Name: Patient Admission Time, dtype: datetime64[ns]
Missing time values: 0
Data type: datetime64[ns]

In [94]:
print(df["Patient Admission Date"].head())
print("Missing dates:",df["Patient Admission Date"].isna().sum())
print("Data type:",df["Patient Admission Date"].dtype)

0   2024-09-09
1   2024-09-09
2   2024-09-09
3   2024-09-09
4   2024-09-09
Name: Patient Admission Date, dtype: datetime64[ns]
Missing dates: 5603
Data type: datetime64[ns]

checking for the merged column

In [93]:
print("Data Type")
print(df["Merged"].dtype)
print("Number of unique values ")
print(df["Merged"].nunique())
print("Missing values ")
print(df["Merged"].isnull().sum())
print("First 20 values")
print(df["Merged"].head(20).tolist())
print(df["Merged"].value_counts().head(10))

Data Type
object
Number of unique values
9185
Missing values
0
First 20 values
['W. Breede', 'Y. Baldetti', 'M. Semerad', 'K. Blaydes', 'F. Dickerson', 'B. Glasman', 'R. Possek', 'H. Cloake', 'G. Tregonna', 'T. Shillaker', 'S. Hebblewaite', 'X. McCart', 'B. Carman', 'K. Brittan', 'L. Week', 'Q. Dalglish', 'E. Norcliff', 'M. Harsent', 'L. Scargle', 'G. Edington']
Merged
L. Pacht        2
X. Lewsy        2
B. Champneys    2
Q. Radish       2
F. Fowlston     2
F. Keogh        2
L. Torald       2
H. Kehoe        2
L. Lovick       2
W. Keyworth     2
Name: count, dtype: int64

In [95]:
#categorical column means it checks is their values exists as inconsistent like
#cardiology
#Cardiology
categorical_columns=[
    "Patient Gender",
    "Patient Race",
    "Department Referral",
    "Patient Admission Flag"
]


for column in categorical_columns:
  print("\n" + column)
  print(df[column].value_counts(dropna=False))

Patient Gender
Patient Gender
Male           4729
Female         4470
Femaleemale      17
Name: count, dtype: int64

Patient Race
Patient Race
White                            2571
African American                 1951
Two or More Races                1557
Asian                            1060
Declined to Identify             1030
Pacific Islander                  549
Native American/Alaska Native     498
Name: count, dtype: int64

Department Referral
Department Referral
NaN                 5400
General Practice    1840
Orthopedics          995
Physiotherapy        276
Cardiology           248
Neurology            193
Gastroenterology     178
Renal                 86
Name: count, dtype: int64

Patient Admission Flag
Patient Admission Flag
Admission        4612
Not Admission    4604
Name: count, dtype: int64

In [96]:
print("Total Rows:",len(df))
print("Unique Patient IDs:",df["Patient Id"].nunique())
print("Duplicated patient IDs:",df["Patient Id"].duplicated().sum())

Total Rows: 9216
Unique Patient IDs: 9216
Duplicated patient IDs: 0

In [97]:
Q1=df["Patient Waittime"].quantile(0.25)
Q3=df["Patient Waittime"].quantile(0.75)

IQR=Q3-Q1

lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR


print("Q1:",Q1)
print("Q2",Q3)
print("IQR:",IQR)
print("Lower Bound:",lower_bound)
print("upper Bound:)

SyntaxError: unterminated string literal (detected at line 14) (2299202041.py, line 14)

In [98]:
#so now we have to find the final missing value audit
missing =df .isnull().sum()
print(missing)

Patient Id                       0
Patient Admission Date        5603
Patient Admission Time           0
Merged                           0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
dtype: int64

In [99]:
missing_percentage=(df.isnull().sum() /len(df))*100
print(missing_percentage)

Patient Id                     0.000000
Patient Admission Date        60.796441
Patient Admission Time         0.000000
Merged                         0.000000
Patient Gender                 0.000000
Patient Age                    0.000000
Patient Race                   0.000000
Department Referral           58.593750
Patient Admission Flag         0.000000
Patient Satisfaction Score    72.688802
Patient Waittime               0.000000
dtype: float64

In [100]:
print("Satisfaction score missing by gender:")
print(df.groupby("Patient Gender")["Patient Satisfaction Score"].apply(lambda x:x .isnull().sum()))

Satisfaction score missing by gender:
Patient Gender
Female         3268
Femaleemale      13
Male           3418
Name: Patient Satisfaction Score, dtype: int64

In [101]:
print(df["Patient Gender"].value_counts(dropna=False))

Patient Gender
Male           4729
Female         4470
Femaleemale      17
Name: count, dtype: int64

In [102]:
print(df[df["Patient Gender"] == "Femalemale"])

Empty DataFrame
Columns: [Patient Id, Patient Admission Date, Patient Admission Time, Merged, Patient Gender, Patient Age, Patient Race, Department Referral, Patient Admission Flag, Patient Satisfaction Score, Patient Waittime]
Index: []

In [104]:
print(df["Patient Gender"].unique())

['Female' 'Male' 'Femaleemale']

In [105]:
for value in df["Patient Gender"].unique():
  print(repr(value))

'Female'
'Male'
'Femaleemale'

In [107]:
print((df["Patient Gender"] == "Femaleemale").sum())

17

In [110]:
#we know that there is a lot of missing values inthe department refferal
#so we have to inspect its actual categories
print(df["Department Referral"].value_counts(dropna=False))

Department Referral
NaN                 5400
General Practice    1840
Orthopedics          995
Physiotherapy        276
Cardiology           248
Neurology            193
Gastroenterology     178
Renal                 86
Name: count, dtype: int64

In [118]:
df["Satisfaction Missing"]=df["Patient Satisfaction Score"].isnull()

In [119]:
#now we have to check how many records are missing vs available
print(df["Satisfaction Missing"].value_counts())

Satisfaction Missing
True     6699
False    2517
Name: count, dtype: int64

In [120]:
#now we need to check whether the missing satisfaction scores is differ by Patient admission Flag
print(
    df.groupby("Patient Admission Flag")["Satisfaction Missing"].sum()
)

Patient Admission Flag
Admission        3377
Not Admission    3322
Name: Satisfaction Missing, dtype: int64

In [125]:
#now we need to check whether the missing satisfaction scores is differ by
#Patient admission Flag in percentage
missing_by_admission=(
    df.groupby("Patient Admission Flag")["Satisfaction Missing"].mean()*100
)
print(missing_by_admission)

Patient Admission Flag
Admission        73.222029
Not Admission    72.154648
Name: Satisfaction Missing, dtype: float64

In [127]:
#so now we have to compare the wait time for recordswith and without satisfactio scores
print(
    df.groupby("Satisfaction Missing")["Patient Waittime"]
    .agg(["count","mean","median","min","max"])
)

                      count       mean  median  min  max
Satisfaction Missing
False                  2517  35.351212    36.0   10   60
True                   6699  35.225556    35.0   10   60

In [129]:
#ok now we have to comapre it with the patient age
print(
      df.groupby("Satisfaction Missing")["Patient Age"]
      .agg(["count","mean","median","min","max"])
      )

                      count       mean  median  min  max
Satisfaction Missing
False                  2517  39.943186    39.0    1   79
True                   6699  39.822063    39.0    1   79

In [133]:
#ok now we have to check the whether the missing satisfaction scores differ
#by Department_referral
df.groupby("Department Referral")["Satisfaction Missing"].agg(["count","sum","mean"])

                     count   sum      mean
Department Referral
Cardiology             248   177  0.713710
Gastroenterology       178   124  0.696629
General Practice      1840  1337  0.726630
Neurology              193   140  0.725389
Orthopedics            995   705  0.708543
Physiotherapy          276   193  0.699275
Renal                   86    63  0.732558

In [134]:
#so we can check all missing department referral
df.groupby("Department Referral",dropna=False)["Satisfaction Missing"].agg(["count","sum","min","max","mean","median"])

                     count   sum    min   max      mean  median
Department Referral
Cardiology             248   177  False  True  0.713710     1.0
Gastroenterology       178   124  False  True  0.696629     1.0
General Practice      1840  1337  False  True  0.726630     1.0
Neurology              193   140  False  True  0.725389     1.0
Orthopedics            995   705  False  True  0.708543     1.0
Physiotherapy          276   193  False  True  0.699275     1.0
Renal                   86    63  False  True  0.732558     1.0
NaN                   5400  3960  False  True  0.733333     1.0

ok now we want to correct all the inconsistencies

In [141]:
df["Patient Gender"]=df["Patient Gender"].replace("Femaleemale","Female")

In [136]:
print(df["Patient Gender"].value_counts())

Patient Gender
Male      4729
Female    4487
Name: count, dtype: int64

In [145]:
#now we want to check again for the categoriccal column
categorical_columns=[
    "Patient Gender",
    "Patient Race",
    "Department Referral",
    "Patient Admission Flag"
]
for column in categorical_columns:
  print("\n" + column)
  print(df[column].value_counts(dropna=False))

Patient Gender
Patient Gender
Male      4729
Female    4487
Name: count, dtype: int64

Patient Race
Patient Race
White                            2571
African American                 1951
Two or More Races                1557
Asian                            1060
Declined to Identify             1030
Pacific Islander                  549
Native American/Alaska Native     498
Name: count, dtype: int64

Department Referral
Department Referral
NaN                 5400
General Practice    1840
Orthopedics          995
Physiotherapy        276
Cardiology           248
Neurology            193
Gastroenterology     178
Renal                 86
Name: count, dtype: int64

Patient Admission Flag
Patient Admission Flag
Admission        4612
Not Admission    4604
Name: count, dtype: int64

In [143]:
print(categorical_columns)

['Patient Gender', 'Patient Race', 'Department Referral', 'Patient Admission Flag']

In [149]:
print(df["Patient Admission Date"].dtype)
print(df["Patient Admission Date"].isnull().sum())
print(df['Patient Admission Date'].min())
print(df['Patient Admission Date'].max())

datetime64[ns]
5603
2023-01-04 00:00:00
2024-12-10 00:00:00

In [154]:
#ok now we want to check the valudations of the patient admission time
print(df["Patient Admission Time"].dtype)
print(df["Patient Admission Time"].isnull().sum())
print(df["Patient Admission Time"].min().time())
print(df["Patient Admission Time"].max().time())

datetime64[ns]
0
00:00:00
23:59:00

In [157]:
print(len(df))
print(df["Patient Id"].nunique())
print(df["Patient Id"].duplicated().sum())

9216
9216
0

In [161]:
print(df["Patient Satisfaction Score"].max())
print(df["Patient Satisfaction Score"].min())
print(df["Patient Satisfaction Score"].dropna().sort_values().unique())
# ok we got all the steps correct ,so we can officially add it a sthe record
print(df["Patient Satisfaction Score"].value_counts().sort_index())

10.0
0.0
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Patient Satisfaction Score
0.0     222
1.0     246
2.0     204
3.0     228
4.0     248
5.0     221
6.0     231
7.0     256
8.0     218
9.0     222
10.0    221
Name: count, dtype: int64

In [164]:
#ok now we want to check the patient waittime validations
print(df["Patient Waittime"].max())
print(df["Patient Waittime"].min())
print(df["Patient Waittime"].sort_values().unique())

60
10
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60]

In [165]:
!cd/content/hospital-patient-satisfaction-analytics

/bin/bash: line 1: cd/content/hospital-patient-satisfaction-analytics: No such file or directory

In [166]:
!git status

fatal: not a git repository (or any of the parent directories): .git

In [170]:
!find "/content/drive/MyDrive" -name "01_Data_Understanding.ipynb" -print

/content/drive/MyDrive/Colab Notebooks/01_Data_Understanding.ipynb

In [172]:
!git clone https://github.com/albinpsabu/hospital-patient-satisfaction-analytics.git /content/hospital-patient-satisfaction-analytics

Cloning into '/content/hospital-patient-satisfaction-analytics'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.